-- Auto-generated by Mechanic Desktop CLI
-- This file is read by Mechanic on addon load
-- Do not edit manually

MECHANIC_LUA_QUEUE = {
	{
		["label"] = "GlidingInfo",
		["code"] = [[local isGliding, canGlide, forwardSpeed = C_PlayerInfo.GetGlidingInfo(); return string.format('GetGlidingInfo: isGliding=%s, canGlide=%s, forwardSpeed=%s', tostring(isGliding), tostring(canGlide), tostring(forwardSpeed))]],
	},
	{
		["label"] = "UnitSpeed",
		["code"] = [[local speed = GetUnitSpeed('player'); return string.format('GetUnitSpeed: %s y/s', tostring(speed))]],
	},
	{
		["label"] = "MapInfo",
		["code"] = [[local mapID = C_Map.GetBestMapForUnit('player'); local isDI = FlightsimLogic and FlightsimLogic.Speed.IsDragonIslesMap(mapID); return string.format('MapID: %s, IsDragonIsles: %s', tostring(mapID), tostring(isDI))]],
	},
	{
		["label"] = "SpeedCalc",
		["code"] = [[local baseSpeed = 8.24; local speed = GetUnitSpeed('player'); local pct = (speed / baseSpeed) * 100; return string.format('Speed calc: %s y/s / 8.24 = %.1f%%', tostring(speed), pct)]],
	},
	{
		["label"] = "ForwardSpeedType",
		["code"] = [[local _, _, fwdSpeed = C_PlayerInfo.GetGlidingInfo(); if fwdSpeed then return string.format('forwardSpeed raw: %s (type: %s)', tostring(fwdSpeed), type(fwdSpeed)) else return 'forwardSpeed: nil' end]],
	}
}
